name       : sdl2-net
version    : 2.2.0
release    : 5
source     :
    - https://github.com/libsdl-org/SDL_net/archive/refs/tags/release-2.2.0.tar.gz : 08d741282c0c22b82ed134f09cd319803132289cae06fb47b5ada2752faf0493
license    : zlib
component  : multimedia.library
summary    : Small sample cross-platform networking library.
description: |
    Small sample cross-platform networking library.
builddeps  :
    - pkgconfig32(sdl2)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
