name       : sdl2-net
version    : 2.0.1
release    : 2
source     :
    - https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.0.1.tar.gz : 15ce8a7e5a23dafe8177c8df6e6c79b6749a03fff1e8196742d3571657609d21
license    : zlib
component  : multimedia.library
summary    : Small sample cross-platform networking library.
description: |
    Small sample cross-platform networking library.
builddeps  :
    - pkgconfig(sdl2)
    - pkgconfig32(sdl2)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
optimize   : speed
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
